# Numpy
1. It is a Python library that provides a multidimensional array object.
2. At the core of the NumPy package, is the ndarray object.
3. This encapsulates n-dimensional arrays of homogeneous data types

In [4]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

## Creating Numpy array
1. First we create list
2. We make this list to array by np.array(list)

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

In [9]:
arr = np.array(my_list)    #list we are making array here by NumPy

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
#nd --> n dimension

## Arange
Return evenly spaced values within a given interval.

arange ( [start,] stop [, step,], dtype = None, *, like=None)

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,20,4)  #start value, stop value, step value

array([ 0,  4,  8, 12, 16])

In [17]:
# end element will be (n-1)

#### 1st arg always be < then 2nd arg

In [19]:
np.arange(30,20)   

array([], dtype=int32)

# 

#### Parameter Tunning --> means using default setting/parameters

In [22]:
np.zeros(5) # parameter tunning

array([0., 0., 0., 0., 0.])

###### 

#### Hyper-parameter Tunning --> means using modified settings/parameters

In [25]:
np.zeros(5, dtype=int) # hyper-parameter tunning

array([0, 0, 0, 0, 0])

###### 

In [27]:
np.zeros((2,10), dtype=int)  # 2 rows & 10 columns

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.zeros((2,10,5), dtype=int)   #(depth, rows , columns), (z,x,y)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [29]:
a = (5,10)
b= (2,5)
print(np.zeros(a))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [30]:
print(np.zeros(b))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


###### 

In [32]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [33]:
np.ones(a)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

#### Only np.ones & np.zeros is allowed 

###### 

## Range
Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.

In [ ]:
r = range(5)

In [ ]:
r

In [ ]:
for i in r:
    print(i)

In [ ]:
R = range(0,20,2)
R

In [ ]:
for i in R:
    print(i)

In [ ]:
list(range(0,10))

###### 

In [ ]:
np.arange(12)

### "arange" is NumPy function whereas "range" is python function

###### 

# Random Function : rand( )
Gives random number from given range

In [ ]:
rand(3,2)

In [ ]:
random.rand(3,2)

In [ ]:
 # np--package, random--module, rand--function

In [ ]:
np.random.rand(4,6) # 4 rows, 6 columns ,,,,, Creates 4 arrays with 6 values in each array

#### np.random.rand(x,y)-- Gives x arrays with y random values in each 

###### 

In [ ]:
np.random.randint(3,6)  # gives random value from given range

#### np.random.randint(x,y)-- Gives a random integer between x & y

###### 

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.randint(2,4)

In [ ]:
np.random.randint(10,20,3) #(start value, last value, no. of int)

###### 

### Generate random values in matrix

In [ ]:
a = np.random.randint(10,40,(5,3,8))
# (first, last, (depth or n, rows, columns))
a

# 

In [46]:
b = np.random.randint(0,10,(15,11))
b

array([[4, 0, 7, 6, 3, 0, 0, 9, 0, 7, 2],
       [3, 5, 1, 9, 0, 3, 2, 7, 7, 9, 3],
       [0, 6, 1, 6, 6, 4, 6, 1, 4, 8, 6],
       [9, 8, 0, 0, 0, 5, 2, 5, 5, 8, 8],
       [5, 9, 4, 5, 2, 9, 7, 9, 4, 2, 1],
       [6, 6, 0, 4, 0, 1, 7, 4, 0, 0, 6],
       [5, 9, 7, 0, 3, 4, 4, 4, 0, 8, 2],
       [1, 3, 5, 5, 3, 4, 0, 8, 0, 8, 0],
       [7, 8, 7, 8, 0, 6, 4, 0, 0, 5, 6],
       [1, 1, 6, 2, 5, 7, 9, 6, 7, 0, 9],
       [7, 3, 6, 5, 7, 1, 3, 4, 9, 9, 1],
       [1, 1, 1, 5, 8, 2, 0, 5, 9, 0, 2],
       [1, 6, 9, 9, 6, 9, 1, 2, 7, 8, 5],
       [4, 8, 5, 5, 5, 3, 2, 9, 7, 7, 1],
       [0, 5, 5, 5, 9, 6, 8, 4, 1, 7, 1]])

In [ ]:
b[1:5]   # Rows Slicing

In [ ]:
b[1,5]

In [ ]:
b[-1]

In [ ]:
b[-1,-4]

In [50]:
b[::-1]  # Reverse Rows upside-down

array([[0, 5, 5, 5, 9, 6, 8, 4, 1, 7, 1],
       [4, 8, 5, 5, 5, 3, 2, 9, 7, 7, 1],
       [1, 6, 9, 9, 6, 9, 1, 2, 7, 8, 5],
       [1, 1, 1, 5, 8, 2, 0, 5, 9, 0, 2],
       [7, 3, 6, 5, 7, 1, 3, 4, 9, 9, 1],
       [1, 1, 6, 2, 5, 7, 9, 6, 7, 0, 9],
       [7, 8, 7, 8, 0, 6, 4, 0, 0, 5, 6],
       [1, 3, 5, 5, 3, 4, 0, 8, 0, 8, 0],
       [5, 9, 7, 0, 3, 4, 4, 4, 0, 8, 2],
       [6, 6, 0, 4, 0, 1, 7, 4, 0, 0, 6],
       [5, 9, 4, 5, 2, 9, 7, 9, 4, 2, 1],
       [9, 8, 0, 0, 0, 5, 2, 5, 5, 8, 8],
       [0, 6, 1, 6, 6, 4, 6, 1, 4, 8, 6],
       [3, 5, 1, 9, 0, 3, 2, 7, 7, 9, 3],
       [4, 0, 7, 6, 3, 0, 0, 9, 0, 7, 2]])

In [52]:
b

array([[4, 0, 7, 6, 3, 0, 0, 9, 0, 7, 2],
       [3, 5, 1, 9, 0, 3, 2, 7, 7, 9, 3],
       [0, 6, 1, 6, 6, 4, 6, 1, 4, 8, 6],
       [9, 8, 0, 0, 0, 5, 2, 5, 5, 8, 8],
       [5, 9, 4, 5, 2, 9, 7, 9, 4, 2, 1],
       [6, 6, 0, 4, 0, 1, 7, 4, 0, 0, 6],
       [5, 9, 7, 0, 3, 4, 4, 4, 0, 8, 2],
       [1, 3, 5, 5, 3, 4, 0, 8, 0, 8, 0],
       [7, 8, 7, 8, 0, 6, 4, 0, 0, 5, 6],
       [1, 1, 6, 2, 5, 7, 9, 6, 7, 0, 9],
       [7, 3, 6, 5, 7, 1, 3, 4, 9, 9, 1],
       [1, 1, 1, 5, 8, 2, 0, 5, 9, 0, 2],
       [1, 6, 9, 9, 6, 9, 1, 2, 7, 8, 5],
       [4, 8, 5, 5, 5, 3, 2, 9, 7, 7, 1],
       [0, 5, 5, 5, 9, 6, 8, 4, 1, 7, 1]])

In [56]:
b[::-2]  # Reverse rows with 2 steps

array([[0, 5, 5, 5, 9, 6, 8, 4, 1, 7, 1],
       [1, 6, 9, 9, 6, 9, 1, 2, 7, 8, 5],
       [7, 3, 6, 5, 7, 1, 3, 4, 9, 9, 1],
       [7, 8, 7, 8, 0, 6, 4, 0, 0, 5, 6],
       [5, 9, 7, 0, 3, 4, 4, 4, 0, 8, 2],
       [5, 9, 4, 5, 2, 9, 7, 9, 4, 2, 1],
       [0, 6, 1, 6, 6, 4, 6, 1, 4, 8, 6],
       [4, 0, 7, 6, 3, 0, 0, 9, 0, 7, 2]])

In [64]:
b.max() #Max value in Matrix

9

In [68]:
b.min() #minimum value in matrix

0

In [72]:
b.mean()  # Mean of all matrix i.e Summation of all values / no. of total values

4.375757575757576

###### 

In [81]:
from numpy import *
a = array([1,2,3,4,5,6,7,8,9])
median(a)      # Middle most value in array

5.0

In [83]:
arr

array([0, 1, 2, 3, 4, 5])

###### 

## .reshape (rows, columns)
Returns an array containing the same data with a new shape.

In [163]:
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### F Is Fortran contiguous layout. Mathematically speaking, column major.

In [161]:
arr.reshape(3,2,order='F')  

array([[0, 3],
       [1, 4],
       [2, 5]])

###### 

### C Is Contiguous layout. Mathematically speaking, row major.

In [171]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

###### 

### A Is any order. Generally don't use this..

In [177]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

###### 

### K Is keep order. Generally don't use this.

In [187]:
arr.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

###### 

## Indexing

In [195]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [251]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [255]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [201]:
mat[5,9] #values at 5th row & 9th column

59

In [203]:
mat[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [215]:
row = 2
col = 5

In [219]:
mat[row,col]

25

#### matrix  [: , column ] --> to see column

In [213]:
mat[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [211]:
mat[:,9].reshape(10,1) # 9th columns

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

### mat[row,:]

In [221]:
mat[row,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### mat[:,column]

In [223]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [225]:
mat[-1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [229]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [237]:
mat[0:10:3]   # Matrix of 0 to 10th row with step of 3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

###### 

In [240]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
mat[2:6,2:4]  # Matrix[ row slicing, column slicing]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [246]:
mat[2:3,2:3]

array([[22]])

###### 

## Masking

In [258]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
id(mat)

2569200284080

In [263]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [265]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [267]:
mat[mat==50]

array([50])

In [269]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

###### 

In [280]:
a = mat[mat<20]
b = mat[mat>80]
c =  np.concatenate((a, b))  # .concatenate() :Join a sequence of arrays along an existing axis.
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 81 82 83 84
 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
